config/routes.rb
Rails.application.routes.draw do
  get 'player/summary'

  root to: 'game#list'
  post 'game/create'

  get 'game/new'
  get 'game/list'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  belongs_to :season

  def avg_score
    player_list.avg_score
  end

  def player_list
    @player_list ||= PlayerList.new(players)
  end

  class << self
    def create_by_params(params)
      params = params.symbolize_keys
      validate_params(params)
      season_id = params[:game]["season_id"].to_i
      game = Game.create!(season_id: season_id)
      4.times do |i|
        user_id = params[:user]["#{i}"].to_i
        role_id = params[:role]["#{i}"].to_i
        score = params[:score]["#{i}"].to_i
        first_shield = params[:shield]["#{i}"].to_i
        is_last_traveller = params[:player]["travel"] == "#{i + 1}"
        is_first_mover = params[:player]["move"] == "#{i + 1}" 
        is_first_picker = params[:player]["pick"] == "#{i + 1}" 
#        logger.debug(params[:player])
        Player.create(user_id: user_id, role_id: role_id, score: score, is_last_traveller: is_last_traveller, is_first_mover: is_first_mover, is_first_picker: is_first_picker, first_shield: first_shield, game: game)
      end
      game
    end

    private
    def validate_params(params)
      users = params[:user]
      roles = params[:role]
      scores = params[:score]
      #is_lasts = params[:is_last_traveller]
      #is_firsts = params[:is_first_mover]
      raise 'duplicate user' unless users.length == users.values.uniq.length
      raise 'duplicate role' unless roles.length == roles.values.uniq.length
      raise 'score empty' unless !scores.values.include?("")
      #raise 'duplicate last traveller' unless is_lasts.values.count("1") <= 1
      #raise 'duplicate first mover' unless is_firsts.values.count("1") <= 1
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  belongs_to :game
  has_one :season, through: :game

  def relative_score
    score - game.avg_score
  end

  def ranking
    scores = game.player_list.scores
    scores.count{ |s| s > score } + 1
  end
end

app/models/player_list.rb
class PlayerList
  attr_accessor :players
  def initialize(players)
    @players = players
  end

  def scores
    return [0] if players.length == 0
    players.map{ |player| player.score}
  end

  def relative_scores
    return [0] if players.length == 0
    players.map{ |player| player.relative_score}
  end

  def avg_score(type = :normal)
    scores = scores_by_type(type)
    scores.mean
  end

  def max_score(type = :normal)
    scores = scores_by_type(type)
    scores.max
  end

  def min_score(type = :normal)
    scores = scores_by_type(type)
    scores.min
  end

  def median_score(type = :normal)
    scores = scores_by_type(type)
    scores.median
  end

  def standard_deviation(type = :normal)
    scores = scores_by_type(type)
    scores.standard_deviation
  end

  def user_count
    attr_count(:user_id)
  end

  def role_count
    attr_count(:role_id)
  end

  def ranking_count
    attr_count(:ranking)
  end

  private
  def attr_count(attr)
    result = {}
    players.each do |p|
      key = p.send attr
      if result[key].nil?
        result[key] = 1
      else
        result[key] += 1
      end
    end
    result.sort.to_h
  end

  def scores_by_type(type)
    if type == :relative
      relative_scores
    elsif type == :normal
      scores
    else
      [-1]
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :games

  class << self
    def max
      return Season.last.id
    end
  end
end

app/models/shield.rb
class Shield < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from StandardError, :with => :handle_error

  def handle_error(e)
    Rails.logger.error e.message
    Rails.logger.error e.backtrace
    puts e.message
    puts e.backtrace
    result = {}
    result[:error_code] = e.message
    result[:error_msg] = e.backtrace.join("<br/>") unless e.class == RuntimeError 
    respond_to do |format|
      format.html{ render :text => result }
    end
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def new
    @game = params[:game] || Game.new
  end

  def create
    @game = Game.create_by_params(params)
  end

  def list
    season_id = (params[:season_id] || Season.max).to_i
    @games = Game.where(season_id: season_id)
    @player_lists = []
    (1..4).each do |i|
      @player_lists << PlayerList.new(Player.joins(:game).where(user_id: i, games:{season_id: season_id}))
    end
    @total_avg_score = @player_lists.map{|pl| pl.avg_score}.inject{|sum, s| sum + s}/4
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def summary
    summary = params[:summary] || {user_id: "", role_id: "", first_shield: "", is_last_traveller: '0', is_first_mover: '0', season_id: Season.max}
    hash = {}
    game_hash = {}
    hash[:user_id] = summary[:user_id] unless summary[:user_id] == ""
    hash[:role_id] = summary[:role_id] unless summary[:role_id] == ""
    hash[:first_shield] = summary[:first_shield] unless summary[:first_shield] == ""
    hash[:is_last_traveller] = true if summary[:is_last_traveller] == '1'
    hash[:is_first_mover] = true if summary[:is_first_mover] == '1'
    hash[:is_first_picker] = true if summary[:is_first_picker] == '1'
    hash[:games] = {}
    hash[:games] = {season_id: summary[:season_id]} unless summary[:season_id] == ""
    @hash = hash
    @player_list = PlayerList.new(Player.joins(:game).where(hash))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper

  def player_info(player)
    concat label_tag("user", player.user.name)
    concat label_tag("role", "(#{player.role.name})")
    bold_style = player.is_last_traveller ? 'bold' : 'normal'
    underline_style = player.is_first_mover ? 'underline' : 'normal'
    pick_style = player.is_first_picker ? '*' : ''
    concat label_tag("score", "  #{player.score}#{pick_style}", style: "font-weight:#{bold_style}; text-decoration:#{underline_style}")
  end
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/game/create.html.erb
<h1>Game#create</h1>
<h3>確認:</h3>
<% game = @game %>
<tr>
  <td><% player_info(game.players[0]) %></td>
  <td><% player_info(game.players[1]) %></td>
  <td><% player_info(game.players[2]) %></td>
  <td><% player_info(game.players[3]) %></td>
</tr>
<br/>
<br/>
<%= button_to("返回",game_list_path, method: :get) %>

app/views/game/list.html.erb
<h1>Game#List</h1>
<%= button_to("新增", game_new_path, method: :get) %>
<%= button_to("統計", player_summary_path, method: :get) %>
<label style="text-decoration:underline">最先行動</label>  <label>最先選角色*</label>  <label style="font-weight:bold">最後先手權</label>
<table>
  <tr>
    <th>id</th>
    <th>date</th>
    <th>player 1</th>
    <th>player 2</th>
    <th>player 3</th>
    <th>player 4</th>
    <th>平均</th>
  </tr>
  <% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>
    <td><%= game.created_at.localtime("+08:00").strftime("%Y-%m-%d %T") %></td>
    <td><% player_info(game.players[0]) %></td>
    <td><% player_info(game.players[1]) %></td>
    <td><% player_info(game.players[2]) %></td>
    <td><% player_info(game.players[3]) %></td>
    <td><%= game.avg_score %></td>
  </tr>
  <% end %>
  <tr>
    <td>-</td>
    <td>平均</td>
    <% 4.times do |i|%>
      <td><%= @player_lists[i].avg_score %></td>
    <% end %>
    <td><%= @total_avg_score %></td>
  </tr>
</table>
<% Season.all.each do |season| %>
<%= button_to(season.name, game_list_path, method: 'get', params: {season_id: season.id}) %>
<% end %>

app/views/game/new.html.erb
<h1>Game#new</h1>
<%= button_to("返回",game_list_path, method: :get) %>
<%= form_for @game, url: {action: "create"} do|f| %>
  <tr>
    <td><label>賽季</label></td>
    <td><%= select("game", "season_id", Season.all.collect {|u| [ u.name, u.id ] }, {selected: Season.last.id, include_blank: false})%></td>
  </tr>
  <tr>
    <td><label>最先行動:</label></td>
    <td><%= select("player", 'move', User.all.collect {|u| [ u.name, u.id ] }, {selected:  1, include_blank: false})%></td>
  </tr>
  <tr>
    <td><label>最先選角色:</label></td>
    <td><%= select("player", 'pick', User.all.collect {|u| [ u.name, u.id ] }, {selected:  1, include_blank: false})%></td>
  </tr>
  <tr>
    <td><label>最後先手權:</label></td>
    <td><%= select("player", 'travel', User.all.collect {|u| [ u.name, u.id ] }, {selected: 1, include_blank: false})%></td>
  </tr>
  <% (0..3).each do |i| %>
    <tr>
      <td><h5><%= "#{i + 1}."%></h5></td>
      <td><label>邊個玩:</label></td>
      <td><%= select("user", i, User.all.collect {|u| [ u.name, u.id ] }, {selected: i + 1, include_blank: false})%></td>
      <td><label>邊個角色:</label></td>
      <td><%= select("role", i, Role.all.reverse.collect {|u| [ u.name, u.id ] }, {selected: 25 - i }) %></td>
      <td><label>分數:</label></td>
      <td><%= number_field("score", i) %></td>
      <td><label>第一個盾:</label></td>
      <td><%= select('shield', i, Shield.all.collect {|u| [ u.name, u.id ] }, {include_blank: false, selected: 1})%></td>
    </tr>
    <br/>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MarcoPoloMarker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/player/summary.html.erb
<h1>Player#summary</h1>
<%= button_to("返回",game_list_path, method: :get) %>
<%= form_tag player_summary_path, method: :get, id: :summary do %>
  <tr>
    <td><label>賽季:</label></td>
    <td><%= select('summary', "season_id", Season.all.collect {|u| [ u.name, u.id ] }, {include_blank: 'all', selected: @hash[:games][:season_id]})%></td>
    <td><label>玩家:</label></td>
    <td><%= select('summary', "user_id", User.all.collect {|u| [ u.name, u.id ] }, {include_blank: 'all', selected: @hash[:user_id]})%></td>
    <td><label>角色:</label></td>
    <td><%= select('summary', "role_id", Role.all.reverse.collect {|u| [ u.name, u.id ] }, {include_blank: 'all', selected: @hash[:role_id]})%></td>
    </br>
    <td><label>只選最後去旅行:</label></td>
    <td><%= check_box('summary', "is_last_traveller", {checked: @hash[:is_last_traveller]}) %></td>
    <td><label>只選最先行動:</label></td>
    <td><%= check_box('summary', "is_first_mover", {checked: @hash[:is_first_mover]}) %></td>
    <td><label>只選最先選角色:</label></td>
    <td><%= check_box('summary', "is_first_picker", {checked: @hash[:is_first_picker]}) %></td>
    </br>
    <label>第一個盾:</label>
    <td><%= select('summary', "first_shield", Shield.all.collect {|u| [ u.name, u.id ] }, {include_blank: 'all', selected: @hash[:first_shield]})%></td>
  </tr>
  <br/>
  <%= submit_tag 'search' %>
<% end %>

<table>
  <tr>
    <th/>
    <th>分數</th>
    <th>相對分數</th>
  <tr>
    <td>平均分</td>
    <td><%= @player_list.avg_score %></td>
    <td><%= @player_list.avg_score(:relative) %></td>
  </tr>
  <tr>
    <td>標準差</td>
    <td><%= @player_list.standard_deviation %></td>
    <td><%= @player_list.standard_deviation(:relative) %></td>
  </tr>
  <tr>
    <td>最高分</td>
    <td><%= @player_list.max_score %></td>
    <td><%= @player_list.max_score(:relative) %></td>
  </tr>
  <tr>
    <td>最低分</td>
    <td><%= @player_list.min_score %></td>
    <td><%= @player_list.min_score(:relative) %></td>
  </tr>
  <tr>
    <td>中位數</td>
    <td><%= @player_list.median_score %></td>
    <td><%= @player_list.median_score(:relative) %></td>
  </tr>
</table>
<br/>

<table>
  <tr>
    <th>名次</th>
    <th>次數</th>
  <% @player_list.ranking_count.each do |k,v| %>
    <tr>
      <td><%= "第#{k}" %></td>
      <td><%= v %></td>
    </tr>
  <% end %>
  </tr>
</table>

<% if @hash[:user_id].nil? %>
  <table>
    <tr>
      <th>玩家</th>
      <th>次數</th>
    <% @player_list.user_count.each do |k,v| %>
      <tr>
        <td><%= User.find_by_id(k).name %></td>
        <td><%= v %></td>
      </tr>
    <% end %>
    </tr>
  </table>
  <br/>
<% end %>

<% if @hash[:role_id].nil? %>
  <table>
    <tr>
      <th>角色</th>
      <th>次數</th>
    <% @player_list.role_count.each do |k,v| %>
      <tr>
        <td><%= Role.find_by_id(k).name %></td>
        <td><%= v %></td>
      </tr>
    <% end %>
    </tr>
  </table>
<% end %>


<style>
form#summary label{
 display: contents;
 margin: 2em;
}
</style>